### ISSUE TITLE
API recommendation

### ISSUE THREAD

**Issue by tblobaum** [blainekasten/shortcut.js#12]
```
function uppercaseInput(e){...}
function validateInput(e){...}

shortcut.on('mod +', function (e) {
    uppercaseInput()
    //..
}).on('mod =', function (e) {
    validateInput()
    //..
})
```

**Comment by blainekasten** [comment]
I do see what you are getting at. It follows some more traditional syntax's. jQuery like.

The down fall of this is that you lose access to the shortcut instance. We'd have to redefine a way to remove listeners, destroy shortcuts, pause/resume etc. I don't think the small syntax change is worth it. 

But thanks for the idea!
